---
title: "Shakun data mapped"
author: "Andrew M. Dolman"
date: "12/15/2016"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r}
library(leaflet) 
library(climproxyrecords)
library(tidyverse)

knitr::opts_chunk$set(cache = T)
```

```{r}

# Produce map
leaflet(data) %>%
    addProviderTiles("CartoDB.Positron") %>%
    addCircleMarkers(lng = ~Lon, lat = ~Lat, radius = 5, fillColor = "darkred", 
                     popup = ~paste(Geo.cluster, Core), fillOpacity = 0.5, stroke = F, data = shakun.metadata) %>%
  clearBounds()

```


```{r}
# Highlight N41
leaflet(data) %>%
    addProviderTiles("CartoDB.Positron") %>%
    addCircleMarkers(lng = ~Lon, lat = ~Lat, radius = 5, fillColor = "darkred", 
                     popup = ~paste(Geo.cluster, Core), fillOpacity = 0.5, stroke = F, data = shakun.metadata) %>%
    addCircleMarkers(lng = ~Lon, lat = ~Lat, radius = 5, fillColor = "Gold", 
                     popup = ~paste(Geo.cluster, Core), fillOpacity = 1, stroke = F,
                     data = filter(shakun.metadata, ID.no == "N41")) %>%
  clearBounds()
```


```{r}
world <- map_data("world")
worldmap <- ggplot(world, aes(x = long, y = lat, group = group)) +
  geom_path(colour = "Darkgrey") +
  coord_map("gall", 0, xlim = c(-180, 180), ylim = c(-90, 90)) +
  scale_y_continuous("Lon", breaks = c(-80, 40, 0, -40, 80)) +
  scale_x_continuous("Lat", breaks = (-4:4) * 45) +
  geom_point(data = shakun.metadata, aes(x = Lon, y = Lat, group = NULL), colour = "Darkred") +
  geom_point(data = filter(shakun.metadata, ID.no == "N41"),
             aes(x = Lon, y = Lat, group = NULL), colour = "Red") +
  theme_bw()+
  theme(axis.text = element_text())
worldmap 
```




```{r}
world <- map_data("world")
worldmap <- ggplot(world, aes(x = long, y = lat, group = group)) +
  geom_path() +
#  coord_map("ortho", orientation = c(-90, 0, 0), ylim = c(-90, -60), xlim = c(-90, -45)) +
  coord_map("ortho", orientation = c(-90, 0, 0), ylim = c(-90, -60), xlim = c(-90, -35)) +
  scale_y_continuous() +
  scale_x_continuous() +
  geom_point(data = shakun.metadata, aes(x = Lon, y = Lat, group = NULL), colour = "Darkred") +
  geom_point(data = filter(shakun.metadata, ID.no == "N41"),
             aes(x = Lon, y = Lat, group = NULL), colour = "Red") +
  theme(axis.text = element_text())
worldmap 
```


```{r}
world <- map_data("world")
worldmap <- ggplot(world, aes(x = long, y = lat, group = group)) +
  geom_path() +
#  coord_map("ortho", orientation = c(-90, 0, 0), ylim = c(-90, -60), xlim = c(-90, -45)) +
  coord_map("ortho", orientation = c(-90, 0, 0), ylim = c(-90, -60)) +
  scale_y_continuous() +
  scale_x_continuous() +
  geom_point(data = shakun.metadata, aes(x = Lon, y = Lat, group = NULL), colour = "Darkred") +
  geom_point(data = filter(shakun.metadata, ID.no == "N41"),
             aes(x = Lon, y = Lat, group = NULL), colour = "Red") +
  theme(axis.text = element_text())
worldmap 
```


```{r}
library(ggmap)

location <- get_map(location = c(lon = 0, lat = -80), zoom = 1, maptype = "hybrid")
ggmap(location)

```

